export const ADD_MOVIE = "ADD_MOVIE"

export const TO_WATCHED = "TO_WATCHED"
export const TO_WATCHLIST = "TO_WATCHLIST"

export const WATCH_LIST_DEL = "WATCH_LIST_DEL"
export const WATCHED_DEL = "WATCHED_DEL"

export const FILTER_WATCHLS = "FILTER_WATCHLS"
export const FILTER_WATCHEDLS = "FILTER_WATCHEDLS"


